# Generated by Django 4.2.1 on 2023-05-23 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cup_id', models.IntegerField(default=-1)),
                ('order', models.CharField(blank=True, max_length=1000, null=True)),
                ('mixable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispenser_id', models.IntegerField(default=-1)),
                ('amount_left', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ingredient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cocktails.ingredient')),
            ],
        ),
    ]
