# Generated by Django 4.2.1 on 2023-06-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dispenser_amount_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cup',
            name='cup_id',
            field=models.CharField(max_length=20),
        ),
    ]
