# Generated by Django 4.2.1 on 2023-05-22 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0008_alter_ingredient_amount_alter_ingredient_unit'),
        ('api', '0003_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispenser_id', models.IntegerField(default=-1)),
                ('ingredient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cocktails.ingredient')),
            ],
        ),
    ]
