# Generated by Django 4.2.1 on 2023-05-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0004_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=1, default=1.0, max_digits=3, null=True),
        ),
    ]
