# Generated by Django 4.2.1 on 2023-05-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0005_alter_ingredient_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='garnish',
            field=models.BooleanField(default=False),
        ),
    ]
