# Generated by Django 4.2.1 on 2023-05-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0007_ingredient_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default='cl', max_length=5),
        ),
    ]
